#!/bin/bash

set -ex

for arch in armeabi armeabi-v7a mips; do
    mkdir -p ${arch}
    rm -rf ${arch}/*btle*.so
    cp $1/libs/${arch}/gatttool-btle    ${arch}/libgatttool-btle.so
    cp $1/libs/${arch}/hcitool-btle     ${arch}/libhcitool-btle.so
done

